CONFIG_LOG=y
CONFIG_LOG_SPEED=y
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_MODE_OVERFLOW=y

CONFIG_CPP=y
CONFIG_GLIBCXX_LIBCPP=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y

CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_CONSOLE=y

CONFIG_GPIO=y

CONFIG_PIX_LIB=y

CONFIG_SHELL=y

CONFIG_ZBUS=y
CONFIG_ZBUS_MSG_SUBSCRIBER=y
#CONFIG_NET_BUF=y
CONFIG_HEAP_MEM_POOL_SIZE=4096

CONFIG_REBOOT=y

CONFIG_SPI=y
#CONFIG_SPI_LOG_LEVEL_DBG=y
CONFIG_CAN=y
CONFIG_CAN_LOG_LEVEL_DBG=y

CONFIG_LED_STRIP=y

CONFIG_WATCHDOG=y
